name: ut_course_advisor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pip:
      - streamlit
      - openai
      - sentence-transformers
      - tiktoken
      - python-dotenv
