[theme]
primaryColor = "#005aa9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f8fc"
textColor = "#1a1a2e"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
